#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Bash prompt
PS1='[\u@\h \W]\$ '

# aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias drmall='sudo docker ps --format '{{.ID}}' | xargs sudo docker rm -f'
alias vpn-up='nmcli con up id Atlassian'

# xrandr
# 2560x1600 for laptop works decently
#  xrandr --display :0 --output eDP-1 --mode 2560x1600
# xrandr --screen 0 --output eDP-1 --mode 1920x1200


# local binaries
export PATH=$PATH:~/.local/bin/:~/go/bin

# nodejs
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

fortune | cowsay

xss-lock -- /usr/bin/i3lock --nofork &

# 34:2e:b7:47:57:8e

export EDITOR=vim

# fzf
# https://unix.stackexchange.com/a/403917

source /usr/share/fzf/completion.bash && source /usr/share/fzf/key-bindings.bash
# When selecting files with fzf, we show file content with syntax highlighting,
# or without highlighting if it's not a source file. If the file is a directory,
# we use tree to show the directory's contents.
# We only load the first 200 lines of the file which enables fast previews
# of large text files.
# Requires highlight and tree: pacman -S highlight tree
export FZF_DEFAULT_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null ||
cat {} || tree -C {}) 2> /dev/null | head -200'"

# Search a file with fzf and then open it in an editor
fzf_then_open_in_editor() {
  local file=$(fzf)
  # Open the file if it exists
  if [ -n "$file" ]; then
    # Use the default editor if it's defined, otherwise Vim
    ${EDITOR:-vim} "$file"
  fi
}
alias fvim='fzf_then_open_in_editor'
